local harness = require "harness"
local describe, it = harness.describe, harness.it
local assert_equal, assert_match, assert_true =
   harness.assert_equal, harness.assert_match, harness.assert_true

local function q(text) return string.format("%q", text) end

local function sh(dir, command)
   local pipe = assert(io.popen(("cd %s && %s 2>&1"):format(q(dir), command)))
   local out = pipe:read("*a")
   pipe:close()
   return out
end

local function write(path, text)
   local handle = assert(io.open(path, "w"))
   handle:write(text)
   handle:close()
end

-- A repository with two committed Lua files that both hold a finding, then one
-- edited and one untouched, so a changed-files scan can tell them apart.
local function repo()
   local dir = harness.scratch_dir("scope")
   sh(dir, "git init -q && git config user.email t@t && git config user.name t")
   write(dir .. "/old.lua", "os.execute(arg[1])\n")
   write(dir .. "/edited.lua", "local x = 1\n")
   write(dir .. "/notes.md", "hello\n")
   sh(dir, "git add -A && git commit -q -m base")
   write(dir .. "/edited.lua", "os.execute(arg[2])\n")
   write(dir .. "/notes.md", "hello again\n")
   return dir
end

-- Run luasec from inside `dir` (the CLI is addressed by absolute path).
local function luasec(dir, args)
   local root = io.popen("pwd"):read("*l")
   local command = q(root .. "/bin/luasec") .. " " .. args
   local pipe = assert(io.popen(("cd %s && %s 2>&1; printf '\\n__EXIT__%%d' $?"):format(q(dir), command)))
   local out = pipe:read("*a")
   pipe:close()
   local code = tonumber(out:match("__EXIT__(%d+)%s*$"))
   return (out:gsub("\n?__EXIT__%d+%s*$", "")), code
end

describe("--scope changed", function()
   it("reports only the file that changed since the base", function()
      local dir = repo()
      local out, code = luasec(dir, "--scope changed --base HEAD .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 1, out)
      assert_match(out, "edited%.lua", out)
      assert_true(not out:find("old.lua", 1, true), "the untouched file is not scanned: " .. out)
      assert_true(not out:find("notes.md", 1, true), "a non-Lua file is never scanned: " .. out)
   end)

   it("says so and exits 0 when nothing changed", function()
      local dir = repo()
      sh(dir, "git add -A && git commit -q -m more")
      local out, code = luasec(dir, "--scope changed --base HEAD .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 0, out)
      assert_match(out, "no changed Lua files", out)
   end)

   it("adds untracked files only with --include-untracked", function()
      local dir = repo()
      write(dir .. "/fresh.lua", "os.execute(arg[3])\n")
      local without = luasec(dir, "--scope changed --base HEAD .")
      local with = luasec(dir, "--scope changed --base HEAD --include-untracked .")
      os.execute("rm -rf " .. q(dir))
      assert_true(not without:find("fresh.lua", 1, true), without)
      assert_match(with, "fresh%.lua", with)
   end)

   it("needs a base when there is none to guess", function()
      local dir = repo()
      sh(dir, "git branch -M trunk")
      local out, code = luasec(dir, "--scope changed .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 2, out)
      assert_match(out, "needs %-%-base", out)
   end)

   it("refuses an unknown scope and a directory that is not a repository", function()
      local dir = repo()
      local bad, bad_code = luasec(dir, "--scope nope .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(bad_code, 2, bad)
      assert_match(bad, "expects full or changed", bad)
      local plain = harness.scratch_dir("scope_norepo")
      write(plain .. "/a.lua", "local x = 1\n")
      local out, code = luasec(plain, "--scope changed --base HEAD .")
      os.execute("rm -rf " .. q(plain))
      assert_equal(code, 2, out)
      assert_match(out, "need a git repository", out)
   end)

   it("scans changed files from a subdirectory", function()
      local dir = harness.scratch_dir("scope_sub")
      sh(dir, "git init -q && git config user.email t@t && git config user.name t")
      sh(dir, "mkdir -p sub")
      write(dir .. "/sub/x.lua", "local x = 1\n")
      write(dir .. "/y.lua", "local y = 1\n")
      sh(dir, "git add -A && git commit -q -m base")
      write(dir .. "/sub/x.lua", "os.execute(arg[1])\n")
      write(dir .. "/y.lua", "os.execute(arg[2])\n")
      local out, code = luasec(dir .. "/sub", "--scope changed --base HEAD .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 1, out)
      assert_match(out, "x%.lua", out)
      assert_true(not out:find("y.lua", 1, true), "a change outside the path is not scanned: " .. out)
   end)
   it("refuses a base that git would read as an option", function()
      local dir = repo()
      local out, code = luasec(dir, "--scope changed --base=--all .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 2, out)
      assert_match(out, "must be a ref, not an option", out)
   end)
end)

describe("--staged", function()
   it("scans only what is in the index", function()
      local dir = repo()
      write(dir .. "/staged.lua", "os.execute(arg[4])\n")
      sh(dir, "git add staged.lua")
      local out, code = luasec(dir, "--staged .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 1, out)
      assert_match(out, "staged%.lua", out)
      assert_true(not out:find("edited.lua", 1, true), "an unstaged edit is not scanned: " .. out)
   end)

   it("is silent and exits 0 when nothing is staged", function()
      local dir = repo()
      local out, code = luasec(dir, "--staged .")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 0, out)
      assert_equal(out:gsub("%s+", ""), "", "a pre-commit hook must print nothing: " .. out)
   end)
   it("needs no path: a pre-commit hook is just luasec --staged", function()
      local dir = repo()
      write(dir .. "/hook.lua", "os.execute(arg[5])\n")
      sh(dir, "git add hook.lua")
      local out, code = luasec(dir, "--staged")
      local none, none_code = luasec(dir, "--scope changed --base HEAD")
      os.execute("rm -rf " .. q(dir))
      assert_equal(code, 1, out)
      assert_match(out, "hook%.lua", out)
      assert_equal(none_code, 1, none)
      assert_match(none, "edited%.lua", none)
   end)
end)
